spring:
  application:
    name: msreservation
  cloud:
    config:
      uri: http://localhost:8888

messages:
  reservation:
    not-found : "Reservation non trouvée"
    bar-not-found : "Bar pour cette reservation non trouvée"
    dto:
      invalid: "Requete non-conforme"
  user:
    not-found: "Utilisateur non trouvé"
    dto:
      invalid: "Requete non-conforme"


