spring:
  application:
    name: msreservation
  cloud:
    config:
      uri: http://localhost:8888
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:db

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,env,info"
  endpoint:
    health:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true

