spring:
  application:
    name: msreservation
  cloud:
    config:
      uri: http://localhost:8888

messages:
  reservation:
    not-found : "Reservation non trouvée"
    dto:
      invalid: "Requete non-conforme"


